test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# S3: 購入請求書（Purchase Invoices）
s3_invoices:
  service: S3
  access_key_id:     <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  region:            <%= ENV.fetch("AWS_REGION") %>          # 例: ap-northeast-1
  bucket:            <%= ENV.fetch("AWS_PURCHASE_INVOICE_BUCKET") %>  # 購入請求書バケット
  upload:
    server_side_encryption: "AES256"  # SSE-S3

# S3: 購入領収書（Purchase Receipts）
s3_receipts:
  service: S3
  access_key_id:     <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  region:            <%= ENV.fetch("AWS_REGION") %>
  bucket:            <%= ENV.fetch("AWS_PURCHASE_RECEIPT_BUCKET") %>  # 購入領収書バケット
  upload:
    server_side_encryption: "AES256"  # SSE-S3

# S3: インセンティブ請求書（Incentive Invoices）
s3_incentive_invoices:
  service: S3
  access_key_id:     <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  region:            <%= ENV.fetch("AWS_REGION") %>
  bucket:            <%= ENV.fetch("AWS_INCENTIVE_INVOICE_BUCKET") %>  # インセンティブ請求書バケット
  upload:
    server_side_encryption: "AES256"  # SSE-S3

# S3: インセンティブ領収書（Incentive Receipts）
s3_incentive_receipts:
  service: S3
  access_key_id:     <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  region:            <%= ENV.fetch("AWS_REGION") %>
  bucket:            <%= ENV.fetch("AWS_INCENTIVE_RECEIPT_BUCKET") %>  # インセンティブ領収書バケット
  upload:
    server_side_encryption: "AES256"  # SSE-S3
